// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzbbarexxdeltwxjvaae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6YmJhcmV4eGRlbHR3eGp2YWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDAzNDMsImV4cCI6MjA2Mjc3NjM0M30.5rRXsfTldQ1zkY7gEtORMUV-UfZfmXWoCwgkOyt0LsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);